# github actions 에서 보이는 이름입니다
name: deploy

# 언제 이 yml 을 작동시키는지를 설명합니다
on:
  # 수동으로 작동시킬 수 있도록 하는 설정입니다
  workflow_dispatch:
  # 어느 브랜치에서든 push 가 발생하면 job 을 실행합니다
  push:
jobs:
  # 이 job 의 이름입니다
  deploy:
    # 우리가 등록한 Github Self Hosted Runner 에서 실행합니다
    runs-on: self-hosted
    # 잡의 구체적인 단계입니다
    steps:
      # 처음 _work 폴더에 github actions 프로그램이 파일을 수정할 권한이 없어서, 권한을 부여해 주기 위한 작업입니다
      # 이 명령을 통해서 이미 있는 폴더에 git pull 을 사용할 수 있습니다
      - name: run deploy!
        run: |
          cd ~
          sudo ./bapo.sh

